server:
  port: 8080

spring:
  application:
    name: stock

  datasource:
    password: password
    url: jdbc:postgresql://localhost:15433/stock
    username: ed
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
